### ISSUE TITLE
LLama-3.2-1B model pruning

### ISSUE THREAD

**Issue by rkinas** [NVIDIA/TensorRT-Model-Optimizer#105]
Hi, 
Unfortunately, in the process of pruning the LLama-3.2-1B model, I cannot convert the model to HF format. 

Docker image:  nvcr.io/nvidia/nemo:dev (downloaded today)
nvidia-modelopt[torch]==0.19.0

1. Convert HF format model to nemo.
```
python /opt/NeMo/scripts/checkpoint_converters/convert_llama_hf_to_nemo.py \
--input_name_or_path data/model_repo/Llama-3.2-1B/ \
--output_path data/model_repo/Llama-3.2-1B-nemo.nemo
```

2. Then I pruned only num_attention_heads from 32 to 24. Rest of parameters is the same as oryginal LLama-3.2-1B model.

```
python /opt/NeMo/examples/nlp/language_modeling/megatron_gpt_prune.py model.restore_from_path=data/model_repo/Llama-3.2-1B-nemo.nemo \
model.tensor_model_parallel_size=1 \
model.pipeline_model_parallel_size=1 \
trainer.num_nodes=1 \
trainer.precision=bf16 \
trainer.devices=1  \
prune.num_attention_heads=24 \
prune.num_query_groups=8 \
prune.ffn_hidden_size=8192 \
prune.hidden_size=2048 \
export.save_path=data/model_repo/Llama-3.2-1B-nemo-pruned/
```

3. Try to convert pruned LLama-3.2 to HF format.

```
python /opt/NeMo/scripts/checkpoint_converters/convert_llama_nemo_to_hf.py \
--hf_output_tokenizer meta-llama/Llama-3.2-1B \
--input_name_or_path data/model_repo/Llama-3.2-1B-nemo-pruned.nemo \
--output_path data/model_repo/Llama-3.2-1B-pruned-hf/
```

Error:
[rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/NeMo/scripts/checkpoint_converters/convert_llama_nemo_to_hf.py", line 273, in <module>
[rank0]:     dtype = convert(args.input_name_or_path, args.output_path, precision=args.precision, cpu_only=args.cpu_only)
[rank0]:   File "/opt/NeMo/scripts/checkpoint_converters/convert_llama_nemo_to_hf.py", line 159, in convert
[rank0]:     qkv_weights = qkv_weights.reshape([qkv_total_dim, head_size, hidden_size])
[rank0]: RuntimeError: shape '[40, 85, 2048]' is invalid for input of size 5242880

**Comment by kevalmorabia97** [comment]
Thanks for submitting the issue. Seems like an issue with the NeMo to HF checkpoint converters. There is a fix here: https://github.com/NVIDIA/NeMo/pull/11230/files#diff-0b3e1492330bd8910ce10e65c1a74cf9f23a1679ad5936a1028fb70277c88dcc

Can you apply the same for your script and see if that is sufficient? Else we can reach out to NeMo team to suggest what else is missing

**Comment by rkinas** [comment]
Thank you for your response and solution. I think the problem is with pruning. The test I ran:
1. LLama-3.2-1B HF format conversion to nemo model.
2. nemo format  to HF model (I applied fix related to the conversion script).

RESULT: the model converted without any problem.


1. LLama-3.2-1B HF format conversion to nemo model.
2. Pruning - as instructed above.
2. Pruned nemo model to HF model (I applied fix related to the conversion script).

RESULT: error

In addition, I noticed that there are inconsistencies in NeMo. NeMo has introduced a new function to convert a LLama-3.2-1B model from HF to nemo with the tag --llama32. I converted it to nano (with --llama32 flag) and tried to convert it back to HF and it did not work.

```
python /opt/NeMo/scripts/checkpoint_converters/convert_llama_hf_to_nemo.py \
--input_name_or_path data/model_repo/Llama-3.2-1B/ \
--output_path data/model_repo/Llama-3.2-1B-nemo.nemo \
--llama32
```

**Comment by kevalmorabia97** [comment]
When converting pruned nemo to HF, I think you also need to modify `<HF_INPUT_PATH>/config.json` to contain pruned values for attention head. Better to create a copy of the folder and then modify and write output to this same modified path. You wont need to copy model weights. The checkpoint converter script assumes Both HF and NeMo paths have same model architecture which is not the case when we have a pruned model.

Let me know if this works

**Comment by rkinas** [comment]
I created separate folder with tokenizer and config. 

```
python /opt/NeMo/scripts/checkpoint_converters/convert_llama_nemo_to_hf.py \
--hf_output_tokenizer data/model_repo/Llama-3.2-1B-pruned-config/  \
--input_name_or_path data/model_repo/Llama-3.2-1B-nemo-pruned.nemo \
--hf_input_path data/model_repo/Llama-3.2-1B-pruned-config/ \
--output_path data/model_repo/Llama-3.2-1B-pruned-hf-final \
--precision bf16
```

config is modified

```
{
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 128000,
  "eos_token_id": 128001,
  "head_dim": 64,
  "hidden_act": "silu",
  "hidden_size": 2048,
  "initializer_range": 0.02,
  "intermediate_size": 8192,
  "max_position_embeddings": 131072,
  "mlp_bias": false,
  "model_type": "llama",
  **"num_attention_heads": 24,**
  "num_hidden_layers": 16,
  "num_key_value_heads": 8,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": {
    "factor": 32.0,
    "high_freq_factor": 4.0,
    "low_freq_factor": 1.0,
    "original_max_position_embeddings": 8192,
    "rope_type": "llama3"
  },
  "rope_theta": 500000.0,
  "tie_word_embeddings": true,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.45.0.dev0",
  "use_cache": true,
  "vocab_size": 128256
}
```

but still error exists.

**Comment by kevalmorabia97** [comment]
Hmm. We havent tried Llama 3.2 before as the architecture is different but don't expect it to make much difference for pruning. Can you try one last think for me please? 

Re-run pruning on pruned.nemo with same pruning parameters and make sure it runs without errors. Basically I want to make sure the pruned.nemo model can be restored again in NeMo framework and forward passes work on it. Then we will know whether something is wrong in pruning or in the checkpoint converter script and I can take it over from that.

**Comment by rkinas** [comment]
Probably convertion script (from nemo to HF):

1. I ran pruning on pruned nemo model and ...
```[NeMo I 2024-11-13 12:14:34 nlp_overrides:1374] Model MegatronGPTModel was successfully restored from /workspace/data/model_repo/Llama-3.2-1B-nemo-pruned.nemo.```

2. Calibration process was OK. 
3. Pruned model saved to data/model_repo/Llama-3.2-1B-nemo-pruned-2.nemo
4. Nemo to HF
```[rank0]: RuntimeError: shape '[40, 42, 1024]' is invalid for input of size 2621440```

**Comment by kevalmorabia97** [comment]
Thanks for verifying this! Do your logs mention which layer has this shape mismatch? We can identify what is missing in the checkpoint converter scripts and suggest a fix to the NeMo team in the ongoing PR: https://github.com/NVIDIA/NeMo/pull/11230

**Comment by rkinas** [comment]
![Image](https://github.com/user-attachments/assets/cab86561-a56e-4277-badf-21f9e82b011f)

Layer 0 :)

**Comment by kevalmorabia97** [comment]
Yes, thats at the QKV weights reshape. Just to confirm you did add the `head_size = model.cfg.get("kv_channels") or (hidden_size // head_num)` fix from the PR right? It seems it is using `head_size = 42` (i.e. `1024//24`) instead of `64` (i.e. `1024 // 32`)

**Comment by rkinas** [comment]
You are right - the solution was to use modified model config.json file and apply converter patch (I applied it but then reverted it to old one). My fault. Finally I have correct pruned model. Thank you for your support!

**Comment by kevalmorabia97** [comment]
Great that it is working now! I will also add the note somewhere in pruning example that for HF to NeMo pruning and back to HF users have to manually update config.json before converting back
