### ISSUE TITLE
[ONNX PTQ] NOT_IMPLEMENTED : Could not find an implementation for EfficientNMS_TRT(1) node with name '/model.23/EfficientNMS_TRT'

### ISSUE THREAD

**Issue by laugh12321** [NVIDIA/TensorRT-Model-Optimizer#110]
**Environment:** Using the Docker container for Model Optimizer built with the [Dockerfile](https://github.com/NVIDIA/TensorRT-Model-Optimizer/blob/main/docker/Dockerfile) provided by the NVIDIA/TensorRT-Model-Optimizer project.

**Issue Description:** I encountered a problem while attempting to quantize an ONNX model that includes the [EfficientNMS](https://github.com/NVIDIA/TensorRT/tree/main/plugin/efficientNMSPlugin) plugin. I followed the guidance provided in [Quantize an ONNX model with custom op](https://github.com/NVIDIA/TensorRT-Model-Optimizer/tree/main/onnx_ptq#quantize-an-onnx-model-with-custom-op), but faced issues when executing the commands.

**Related Files:** [yolo11x.onnx](https://drive.google.com/file/d/1rdCpwxuQPvfvXuVedkBwJToyzrz8zTnd/view?usp=drive_link), [calib.npy](https://drive.google.com/file/d/10k7HQb7kfcXWaWxiOJs9HjE2FllSNWU7/view?usp=drive_link)

```
$ python -m modelopt.onnx.quantization --onnx_path=yolo11x.onnx --quantize_mode=int8 --calibration_data=calib.npy --calibration_method=entropy --output_path=yolo11x.quant.onnx --trt_plugins=/usr/local/lib/python3.10/dist-packages/tensorrt_libs/libnvinfer_plugin.so
Loading extension modelopt_round_and_pack_ext...
INFO:root:Model with ORT support is saved to yolo11x_ort_support.onnx. Model contains custom ops: ['EfficientNMS_TRT'].
INFO:root:Model yolo11x_ort_support.onnx with opset_version 11 is loaded.
INFO:root:Model is cloned to yolo11x_opset13.onnx with opset_version 13.
INFO:root:Model is cloned to yolo11x_named.onnx after naming the nodes.
2024-11-28 09:05:25.990982051 [W:onnxruntime:, transformer_memcpy.cc:74 ApplyImpl] 2 Memcpy nodes are added to the graph main_graph for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.
Traceback (most recent call last):
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.10/dist-packages/modelopt/onnx/quantization/main.py", line 228, in <module>
main()
File "/usr/local/lib/python3.10/dist-packages/modelopt/onnx/quantization/main.py", line 201, in main
quantize(
File "/usr/local/lib/python3.10/dist-packages/modelopt/onnx/quantization/quantize.py", line 292, in quantize
nodes_to_exclude = find_nodes_from_mha_to_exclude(
File "/usr/local/lib/python3.10/dist-packages/modelopt/onnx/quantization/graph_utils.py", line 710, in find_nodes_from_mha_to_exclude
session = create_inference_session(model.SerializeToString(), calibration_eps)
File "/usr/local/lib/python3.10/dist-packages/modelopt/onnx/quantization/ort_utils.py", line 42, in create_inference_session
return ort.InferenceSession(
File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in init
self._create_inference_session(providers, provider_options, disabled_optimizers)
File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 483, in _create_inference_session
sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for EfficientNMS_TRT(1) node with name '/model.23/EfficientNMS_TRT'
```

**Comment by chjej202** [comment]
1. go to _/usr/local/lib/python3.10/dist-packages/modelopt/onnx/quantization_ directory.

2. open _ort_utils.py_ 
 
3. change a code to add "trt_extra_plugin_lib_paths" as an execution provider option of the function _create_inference_session_ (you can refer __create_inference_session_with_ep_config_ function located in _ort_patching.py_ file to modify the function )

4. Now, you can try ONNX PTQ.

**Comment by laugh12321** [comment]
Hello @chjej202,

I have followed the steps you provided and attempted to resolve the issue, but the problem persists. The error message I'm encountering is:

`onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for EfficientNMS_TRT(1) node with name '/model.23/EfficientNMS_TRT'`

Upon further inspection, I've realized that modifying the `trt_extra_plugin_lib_paths` parameter in `configure_ort` is actually unnecessary because the path to the TensorRT plugin is already specified when using the `--trt_plugins` argument in the command line.

![Image](https://github.com/user-attachments/assets/c15dd008-7cdf-42f3-8be2-cc1ab5ab5086)

**Comment by chjej202** [comment]
This is a bug from NVIDIA.

The problem of nvidia-modelopt is that _create_inference_session_ function in _ort_utils.py_ does not use the parameter set in _configure_ort_. 

```python
def create_inference_session(onnx_path_or_model: Union[str, bytes], calibration_eps: List[str]):
    """Create an ORT InferenceSession."""
    sess_options = ort.SessionOptions()
    sess_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL
    return ort.InferenceSession(
        onnx_path_or_model,
        sess_options=sess_options,
        providers=_prepare_ep_list(calibration_eps),
    )   

```

You have to change the execution provider option. 
__create_inference_session_with_ep_config_ in _ort_patching.py_ is a good example to change the code.
This function shows how to pass and set _trt_extra_plugin_lib_paths_ to the onnxruntime execution provider.

**Comment by laugh12321** [comment]
@chjej202 Thanks it works.
