### ISSUE TITLE
Ffail to quant onnx(weight stored with fp16) to int8 because of overflow

### ISSUE THREAD

**Issue by tp-nan** [NVIDIA/TensorRT-Model-Optimizer#18]
Hi, I failed to  quant  onnx(weight stored with fp16) to int8 because of overflow.

The following code is from modelopt.onnx.quantization.ort_patching
```python
threshold = max(abs(min_value), abs(max_value))

if tensor in histogram_collector.histogram_dict:
    old_histogram = histogram_collector.histogram_dict[tensor]
    histogram_collector.histogram_dict[tensor] = histogram_collector.merge_histogram(
        old_histogram, data_arr, min_value, max_value, threshold
    )
else:
    hist, hist_edges = np.histogram(
        data_arr, histogram_collector.num_bins, range=(-threshold, threshold)
    )
```

in my case threshold is 54800, then the value of [threshold - (-threshold)] is overflow for fp16.

How can I fix this?

**Comment by i-riyad** [comment]
Can you share the ONNX model and full exception stacktrace?
Also you can try `--calibration_method=minmax` command line parameter in the meantime.
