### ISSUE TITLE
[BUG] The fp8 kv cache quantization result is wrong

### ISSUE THREAD

**Issue by DearPlanet** [NVIDIA/TensorRT-Model-Optimizer#20]
I tried to use `llm_ptq/hf_ptq.py` to quantize to fp8 format for llama2 model. 
```
python llm_ptq/hf_ptq.py --pyt_ckpt_path ~/Llama-2-7b-hf --qformat fp8 --export_path ../llama2-7B-kvquant-mtq
```
But the kv cache scale params saved in output .safetensor seems abnormal, I pick up the kv cache scales with the code below:
```
from safetensors.torch import safe_open

safetensor_model_path = "~/workspace_for_pr/Qwen1.5-7B-kvquant-mtq/rank0.safetensors"

def load_safetensor(filename: str):
    with safe_open(filename, framework="pt") as f:
        for name in f.keys():
            param = f.get_tensor(name)
            yield name, param

for name, param in load_safetensor(safetensor_model_path):
    if "kv_cache" in name:
        print(name)
        print(param)
```

The outputs are:
```
transformer.layers.0.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.1.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.10.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.11.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.12.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.13.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.14.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.15.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.16.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.17.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.18.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.19.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.2.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.20.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.21.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.22.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.23.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.24.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.25.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.26.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.27.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.28.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.29.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.3.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.30.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.31.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.4.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.5.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.6.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.7.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.8.attention.kv_cache_scaling_factor
tensor([1.])
transformer.layers.9.attention.kv_cache_scaling_factor
tensor([1.])
```
All scales were set to `1`, which is not match to the console outputs.

-------

Additionally, if I want to quant **only kv cache** to fp8, which config should I take in `llm_ptq/hf_ptq.py`? 
```
QUANT_CFG_CHOICES = {
    "int8": mtq.INT8_DEFAULT_CFG,
    "int8_sq": mtq.INT8_SMOOTHQUANT_CFG,
    "fp8": mtq.FP8_DEFAULT_CFG,
    "int4_awq": mtq.INT4_AWQ_CFG,
    "w4a8_awq": mtq.W4A8_AWQ_BETA_CFG,
}
```

**Comment by cjluo-nv** [comment]
With our current study, we recommend to use the default value 1 for FP8 kv cache quantization scaling factor. And the TRT LLM also follows the same rule. So the scaling factor is set to 1 even if the calibration process may get a different number.

Additionally, if I want to quant only kv cache to fp8, which config should I take in llm_ptq/hf_ptq.py?
1) I think you can still use fp8, but throw away the other scaling factors in the exported checkpoint.
2) Modify the export config.json and set `quant_algo` to null.

Or simply use a non quantized TRT LLM checkpoint, set the `kv_cache_quant_algo` to "FP8". And add the additional kv_cache_scaling_factor in the safetensors file.

**Comment by DearPlanet** [comment]
Thanks for your explanation @cjluo-omniml !  
However, I still have a few questions:
1. Why recommend setting the scaling factor to 1? Is this consideration based on inference performance?
2. If all scaling factors are set to 1, how much more would the accuracy loss be compared to using scaling factors from calibration? Are there any references or information that can explain it?

**Comment by RalphMao** [comment]
Hi @DearPlanet , this recommendation is based on both empirical accuracy study and implementation difficulty. We tested some models with FP8 KV cache scaling factors=1 and it gives decent accuracy. In addition, the implementation of various LLM models on Huggingface makes it difficult to extract the KV cache scaling factors across all models.

That being said, we are working on provide an option to extract KV cache scaling factors across all models, which should be released in one month or so

**Comment by DearPlanet** [comment]
Got it. Thank you for your explanation @RalphMao !
