### ISSUE TITLE
Request for Documentation: awq_lite, awq_clip, and awq_full

### ISSUE THREAD

**Issue by stoical07** [NVIDIA/TensorRT-Model-Optimizer#25]
The [quantization documentation for TensorRT Model Optimizer](https://nvidia.github.io/TensorRT-Model-Optimizer/reference/generated/modelopt.torch.quantization.config.html#quantization-configs) does not provide explanations for the `awq_lite`, `awq_clip`, and `awq_full` algorithms used in the `INT4_AWQ_CFG` configuration.

- Could you please clarify the differences between these three algorithms?
-  What parameters are supported for each algorithm? 
    - For example, I would like to know what `max_co_batch_size` does in the context of `awq_full` and `awq_clip`. 
    - What are the default values for these parameters?
- Are there any other undocumented parameters for quantization with AWQ?

Here is the relevant configuration snippet:

```python
INT4_AWQ_CFG = {
    "quant_cfg": {
    "*weight_quantizer": {"num_bits": 4, "block_sizes": {-1: 128}, "enable": True},
    "*input_quantizer": {"enable": False},
    "*lm_head*": {"enable": False},
    "*block_sparse_moe.gate*": {"enable": False},  # Skip the MOE router
    "default": {"enable": False},
    },
    "algorithm": {"method": "awq_lite", "alpha_step": 0.1},
    # "algorithm": {"method": "awq_full", "alpha_step": 0.1, "max_co_batch_size": 1024},
    # "algorithm": {"method": "awq_clip", "max_co_batch_size": 2048},
}
```

Thank you for your help! :pray:

**Comment by realAsma** [comment]
Sorry about the lack of documentation. We are working on providing better documentation. 
The original AWQ as implemented in https://github.com/mit-han-lab/llm-awq have two parts:

1. `awq_lite`: In this method, a scaling factor which minimizes the output difference after quantization is applied. See section 3.2 in [AWQ](https://arxiv.org/pdf/2306.00978) paper for more details. 
Here is a workaround for now to get arguments for `awq_lite`:
```
>>> import modelopt.torch.quantization.model_calib as model_calib
>>> help(model_calib.awq_lite)
```
By default, ModelOpt performs `awq_lite`.

2. `awq_clip` - In this method the amax for per-group quantization is searched. This search requires much more compute. To avoid any OOM, the linear layer weights are batched along the `out_features` dimension (of batch size `max_co_batch_size`).  `awq_clip` calibration also takes longer than `awq_lite`
We found `awq_clip` to be similar in regaining accuracy to that of `awq_lite`. 
For now, to learn more about `awq_clip` arguments, please do:
```
>>> import modelopt.torch.quantization.model_calib as model_calib
>>> help(model_calib.awq_clip)
```

`awq_full` performs `awq_lite` followed by `awq_clip` - `awq_full` might slightly improve the model accuracy. But the calibration time is longer as well.

**Comment by ghost** [comment]
Thanks for the fast and detailed response! Appreciate the explanation and workarounds. The ModelOpt library is really useful, and I'm looking forward to upcoming releases and improved documentation! 😊
