### ISSUE TITLE
Python 3.12 - error on pip install

### ISSUE THREAD

**Issue by klyack** [NVIDIA/TensorRT-Model-Optimizer#26]
pip install nvidia-modelopt
> ERROR: Could not find a version that satisfies the requirement nvidia-modelopt (from versions: none)
> ERROR: No matching distribution found for nvidia-modelopt

Latest TensorRT (10.0.1.6) supports python 3.12 but nvidia-modelopt supports only 3.11 so I can't run a stable diffusion demo

**Windows 11    CUDA 12.1    Python 3.12   TensorRT 10.0.1.6**

**Comment by kevalmorabia97** [comment]
Python 3.12 support might be added in the next release. For now, please use python < 3.12
