### ISSUE TITLE
Onnx Quantization doesn't have quantize method

### ISSUE THREAD

**Issue by yixzhou** [NVIDIA/TensorRT-Model-Optimizer#31]
Hi, 

I have just installed the TensorRT-Model_Optimizer using `pip install "nvidia-modelopt[all]" --no-cache-dir --extra-index-url https://pypi.nvidia.com`. I was then using it to quantize a onnx model following the documentation listed [here](https://nvidia.github.io/TensorRT-Model-Optimizer/guides/_onnx_quantization.html). I have also installed trt10 using `pip install tensorrt`. However, when i run 
```
import modelopt.onnx.quantization as moq
moq.quantize(
    onnx_path=onnx_path,
    calibration_data=calibration_data,
    output_path="quant.onnx",
    quantize_mode="int8",
)
```
I got `AttributeError: module 'modelopt.onnx.quantization' has no attribute 'quantize'`. Could you please advise? 

Thanks!

**Comment by i-riyad** [comment]
Use `import modelopt.onnx.quantization.quantize as moq` for now, we will fix this in next release.
