### ISSUE TITLE
int8 diffuser smoothquant  will not generate good images

### ISSUE THREAD

**Issue by 13301338176** [NVIDIA/TensorRT-Model-Optimizer#32]
https://github.com/NVIDIA/TensorRT-Model-Optimizer/blob/6355a47712a6c1a7a7ffd6af75bd6bfb84ac5b21/diffusers/quantization/utils.py#L80C23-L80C49

when enable smoothquant , image quality is not good.

**Comment by jingyu-ml** [comment]
Which models did you use, and could you share your command lines and detailed settings?

**Comment by Edwardf0t1** [comment]
Close the issue as no further response from the user.
