### ISSUE TITLE
[Question] Does the quantized model run in full precision or int8 precision?

### ISSUE THREAD

**Issue by leeeizhang** [NVIDIA/TensorRT-Model-Optimizer#35]
I used the modelopt to quantize my models into the int8 ONNX model. 
However, when I visualize its ONNX graph, I am not sure whether it is computing in full precision or int8 precision.

![image](https://github.com/NVIDIA/TensorRT-Model-Optimizer/assets/43229014/68f5ee7b-0b8a-41ff-998d-3c99d03b84a3)

It seems like the input and weights are quantized into int8 to store in GPU memory. But before the `matmul` operations, these inputs and weights are still dequantized into full precision (e.g., fp32) for computing. Correct me if I am wrong.

I also profiled its execution runtime, and the kernel names are: 
`sm80_xmma_gemm_i8f32_i8i32_f32_tn_n_tilesize128x128x64_stage3_warpsize2x2x1_tensor16x8x32_execute_kernel_trt`
`sm80_xmma_gemm_f32f32_tf32f32_f32_nn_n_tilesize64x128x16_stage4_warpsize2x2x1_tensor16x8x8_execute_kernel_trt`
`sm80_xmma_gemm_i8f32_i8i32_f32_tn_n_tilesize128x128x64_stage3_warpsize2x2x1_tensor16x8x32_fused`

So what do `i8f32` and `i8i32` mean? Does it mean the `int8` weights/inputs are converted into `f32` or `int32`?

**Comment by realAsma** [comment]
@leeeizhang your ONNX graph looks correct to me. TRT will recognize the Q/DQ layers before matmul and replace it with quantized matmul (i.e, in TRT input and weights are quantized to int8 and the int8 GEMM will be used for matmul)

**Comment by leeeizhang** [comment]
> @leeeizhang your ONNX graph looks correct to me. TRT will recognize the Q/DQ layers before matmul and replace it with quantized matmul (i.e, in TRT input and weights are quantized to int8 and the int8 GEMM will be used for matmul)

LGTM! Many thanks!
