### ISSUE TITLE
What is the difference between nvidia-ammo and TensorRT-Model-Optimizer ?

### ISSUE THREAD

**Issue by lix19937** [NVIDIA/TensorRT-Model-Optimizer#4]
What is the difference between nvidia-ammo and TensorRT-Model-Optimizer ?   

And I see TensorRT-Model-Optimizer not full open source ?

**Comment by kevalmorabia97** [comment]
@lix19937 starting from version 0.11, `nvidia-ammo` is renamed as `nvidia-modelopt`. There are some bw breaking changes as mentioned in the changelog [here](https://nvidia.github.io/TensorRT-Model-Optimizer/reference/0_versions.html) but overall they are the same.
