### ISSUE TITLE
the supporting models in modelopt.torch.quantization

### ISSUE THREAD

**Issue by XA23i** [NVIDIA/TensorRT-Model-Optimizer#42]
Hi, I see that we can quantize our model by modelopt.torch.quantization.quantize(model, ...). I am wondering what are the supporting models, does any pytorch model make sense?

**Comment by Edwardf0t1** [comment]
Thanks for your interest and question. Please check our supported model list [here](https://github.com/NVIDIA/TensorRT-Model-Optimizer/tree/main/llm_ptq#model-support-list).

**Comment by XA23i** [comment]
Thank you for quick reply. By the way, what can i do to quantize models that are out of the supporting lists.

**Comment by jingyu-ml** [comment]
Yes, you can, as long as it is a standard PyTorch-based model. @XA23i

**Comment by XA23i** [comment]
That's great. I will have a try.

**Comment by hchings** [comment]
@XA23i Can you share what models you'd like to quantize but are not on the support list?
