### ISSUE TITLE
Adding Phi 3 Vision quantization support

### ISSUE THREAD

**Issue by iibw** [NVIDIA/TensorRT-Model-Optimizer#43]
Support for Phi 3 is almost complete. It seems like this library is just missing Phi 3 Vision. Given that every other Phi 3 LLM is supported and there is multimodal support already for LLaVa, it seems like it wouldn't be too difficult to add Phi 3 Vision quantization support. Phi 3 Vision is a very useful LLM so I think it would be worth it.

Thanks for your work!

**Comment by hchings** [comment]
HI @iibw , we'll see wether we have the bandwidth to support this in our upcoming releases and keep you posted if things are confirmed.

**Comment by hchings** [comment]
Hi @iibw, Phi 3 Vision FP8 will be supported in TensorRT Model Optimizer v0.17 release, which will be public in early Sept. Thanks for the wait and I'll close this issue.
