### ISSUE TITLE
'TensorQuantizer' object has no attribute 'clip'

### ISSUE THREAD

**Issue by YixuanSeanZhou** [NVIDIA/TensorRT-Model-Optimizer#62]
When enabling learned amax, with default INT8 config, I got the following error when inference

```
[1m'TensorQuantizer' object has no attribute 'clip'[0m
```

Could you please help figure out what I did was wrong here? Thanks in advance.

**Comment by realAsma** [comment]
@YixuanSeanZhou , Apologies for the late reply. This is a bug in ModelOpt. I am creating a fix for this in ModelOpt 0.17.

**Comment by realAsma** [comment]
This bug is fixed in the upcoming ModelOpt 0.17 release.
