### ISSUE TITLE
Quantized Model Runs Very Slow (Unable to load extension modelopt_cuda_ext and falling back to CPU version)

### ISSUE THREAD

**Issue by relaxtheo** [NVIDIA/TensorRT-Model-Optimizer#67]
I have tried to quantize a model by following the guide ([PyTorch Quantization — Model Optimizer 0.15.0](https://nvidia.github.io/TensorRT-Model-Optimizer/guides/_pytorch_quantization.html)), and I can get the quantized model, and runs the quantized model on original data, the accuracy get a bit worse which is acceptable, however it runs much slower (around 2 times).

And debugging run in vs.code, I can see such a message “Unable to load extension modelopt_cuda_ext and falling back to CPU version.”, but no such message running straightly in system by python command. 

What is the modelopt_cuda_ext? How to install it or how to fix this problem? Thank you.

**Comment by realAsma** [comment]
` modelopt_cuda_ext` contains cuda kernels for simulated quantization. For some quantization formats such as INT8, we have relatively slower CPU simulated quantization fallback.

> And debugging run in vs.code, I can see such a message “Unable to load extension modelopt_cuda_ext and falling back to CPU version.”, but no such message running straightly in system by python command.

 This might be related to environment setup. The environment might not be set up correctly for your vscode debugging (Looks like your GPU and cuda support the kernels since you dont see this message while running straight from command line).

**Comment by realAsma** [comment]
> I can get the quantized model, and runs the quantized model on original data, the accuracy get a bit worse which is acceptable, however it runs much slower (around 2 times).

ModelOpt Pytorch quantization performs simulated quantization as explained in https://nvidia.github.io/TensorRT-Model-Optimizer/guides/_pytorch_quantization.html

> ModelOpt quantization is fake quantization, which means it only simulates the low-precision computation in PyTorch. Real speedup and memory saving should be achieved by exporting the model to deployment frameworks.

The deployment frameworks are:

TensorRTLLM or VLLM for LLMs
TensorRT via ONNX for regular models

**Comment by relaxtheo** [comment]
modelopt_cuda_ext seems not the critical issue, by my test the quantized model runs very slow either with or without the  modelopt_cuda_ext load message.

I have tried to reproduce the problem by resent152. I trained the pre-trained resnet152 on 'hymenoptera_data', and quantize the trained model. The original trained model requires less than 2s, and quantized model requires almost 9s. 

t2q.py.txt is the code to quantized the model, and t2t.py.txt is the test code for quantized model and original model.
[t2q.py.txt](https://github.com/user-attachments/files/17001818/t2q.py.txt)
[t2t.py.txt](https://github.com/user-attachments/files/17001817/t2t.py.txt)

Below is the log:
(pruning) user@server/data/WS/PruningWS/code$ python t2at.py

/data/WS/anaconda3/envs/pruning/lib/python3.11/site-packages/modelopt/torch/quantization/tensor_quant.py:92: FutureWarning: torch.library.impl_abstract was renamed to torch.library.register_fake. Please use that instead; we will remove torch.library.impl_abstract in a future version of PyTorch.

scaled_e4m3_abstract = torch.library.impl_abstract(“trt::quantize_fp8”)(

BEGINING 1…

BEGINING 2…

ORIGINAL: 1.84156, 1.51373

/data/WS/anaconda3/envs/pruning/lib/python3.11/tempfile.py:934: ResourceWarning: Implicitly cleaning up <TemporaryDirectory ‘/tmp/tmpjfip2iuh’>

_warnings.warn(warn_message, ResourceWarning)

(pruning) user@server/data/WS/PruningWS/code$ python t2at.py

/data/WS/anaconda3/envs/pruning/lib/python3.11/site-packages/modelopt/torch/quantization/tensor_quant.py:92: FutureWarning: torch.library.impl_abstract was renamed to torch.library.register_fake. Please use that instead; we will remove torch.library.impl_abstract in a future version of PyTorch.

scaled_e4m3_abstract = torch.library.impl_abstract(“trt::quantize_fp8”)(

/data/WS/PruningWS/code/t2at.py:86: FutureWarning: You are using torch.load with weights_only=False (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See [pytorch/SECURITY.md at main · pytorch/pytorch · GitHub](https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models) for more details). In a future release, the default value for weights_only will be flipped to True. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via torch.serialization.add_safe_globals. We recommend you start setting weights_only=True for any use case where you don’t have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.

model_ft = mto.restore_from_modelopt_state(model_ft, torch.load(quantized_opt_file))

Inserted 782 quantizers

/data/WS/anaconda3/envs/pruning/lib/python3.11/site-packages/modelopt/torch/quantization/nn/modules/tensor_quantizer.py:837: UserWarning: Could not initialize the quantizer states for maxpool.input_quantizer. The quantizer states after load_state_dict could be in the wrong device. Please move the modules to the correct device after loading the state dict.

warnings.warn(warning_msg, UserWarning)

/data/WS/anaconda3/envs/pruning/lib/python3.11/site-packages/modelopt/torch/quantization/nn/modules/tensor_quantizer.py:837: UserWarning: Could not initialize the quantizer states for avgpool.input_quantizer. The quantizer states after load_state_dict could be in the wrong device. Please move the modules to the correct device after loading the state dict.

warnings.warn(warning_msg, UserWarning)

/data/WS/anaconda3/envs/pruning/lib/python3.11/site-packages/modelopt/torch/quantization/nn/modules/tensor_quantizer.py:740: UserWarning: maxpool.input_quantizer: No ‘_amax’ buffer to load amax into. '_amax` will be created as WAR for now. This behavior will change in future.

warnings.warn(

/data/WS/anaconda3/envs/pruning/lib/python3.11/site-packages/modelopt/torch/quantization/nn/modules/tensor_quantizer.py:740: UserWarning: avgpool.input_quantizer: No ‘_amax’ buffer to load amax into. '_amax` will be created as WAR for now. This behavior will change in future.

warnings.warn(

BEGINING 1…

Loading extension modelopt_cuda_ext…

BEGINING 2…

QUANTIZE: 9.27202, 8.82052

/data/WS/anaconda3/envs/pruning/lib/python3.11/tempfile.py:934: ResourceWarning: Implicitly cleaning up <TemporaryDirectory ‘/tmp/tmprm3d_3jm’>

_warnings.warn(warn_message, ResourceWarning)

**Comment by cjluo-nv** [comment]
`quantized model runs very slow either with or without the modelopt_cuda_ext load message` Could you explain more?

Including the reproduce command, the measured time and the expectation in terms of the slowness?

**Comment by relaxtheo** [comment]
@cjluo-omniml 
quantized model runs very slow either with or without the modelopt_cuda_ext load message Could you explain more?
- It seems require quite long time to load the modelopt_cuda_ext, so I run the inference 2 times, and we can see this message in first run, and no such message in second run, and they all run much slower than original model.

Including the reproduce command, the measured time and the expectation in terms of the slowness?
- Please see my previous comment which has the test code, and the log log shows the original model running only around 1.8s, and the quantized model running around 9s. Huge difference.

**Comment by realAsma** [comment]
@relaxtheo 

> It seems require quite long time to load the modelopt_cuda_ext, so I run the inference 2 times, and we can see this message in first run, and no such message in second run, and they all run much slower than original model.

This is correct behavior. Loading `modelopt_cuda_ext` the very first time will take longer since the simulation kernel is being compiled and cached. In subsequent runs, loading `modelopt_cuda_ext` could take ~5 minutes. 

In one run,  `modelopt_cuda_ext` only needs to be loaded once. This is why you see the `Loading extension modelopt_cuda_ext…` in the first inference run and not in the second inference run.

> Please see my previous comment which has the test code, and the log log shows the original model running only around 1.8s, and the quantized model running around 9s. Huge difference.

`modelopt.torch.quantization` performs simulated quantization. This simulated quantization is slower than un-quantized model forwarding. Real speed up should come after deployment to TensorRT / TensorRT-LLM (this is mentioned in the documentation [here](https://nvidia.github.io/TensorRT-Model-Optimizer/guides/_pytorch_quantization.html#pytorch-quantization).

The simulated quantization overhead also depends on the model and the dataset. For larger models such as LLMs, the matrix multiplication takes quite a bit of time - because of this the simulation quantization overhead is less (it could make the model forward  time 2X longer). For smaller models such as this, simulated quantization could becomes the main overhead and make the model significantly slower.

Either ways, the simulated quantization should only be used for quantization aware training or quick evaluation before deploying to real frameworks (and not for any real inference).

**Comment by relaxtheo** [comment]
I am trying to deploy my quantized resnet model to tensor-llm.

By following the "https://nvidia.github.io/TensorRT-Model-Optimizer/deployment/1_tensorrt_llm_deployment.html", I am trying to export it by:

    from modelopt.torch.export import export_tensorrt_llm_checkpoint

    with torch.inference_mode():
        export_tensorrt_llm_checkpoint(
            model_ft,  # The quantized model.
            'resnet',  # The type of the model as str, e.g gptj, llama or gptnext.
            torch.float16,  # the weights data type to export the unquantized layers.
            './',  # The directory where the exported files will be stored.
            1,  # The number of GPUs used in the inference time for tensor parallelism.
            1,  # The number of GPUs used in the inference time for pipeline parallelism.
        )

and get following error:

Cannot export model to the model_config. The modelopt-optimized model state_dict (including the quantization factors) is saved to modelopt_model.0.pth using torch.save for further inspection.
Detailed export error: Cannot find valid model metadata config in model
Traceback (most recent call last):
  File "/home/theo/anaconda3/envs/modelopt0.17/lib/python3.10/site-packages/modelopt/torch/export/model_config_export.py", line 446, in export_tensorrt_llm_checkpoint
    for tensorrt_llm_config, weights in torch_to_tensorrt_llm_checkpoint(
  File "/home/theo/anaconda3/envs/modelopt0.17/lib/python3.10/site-packages/modelopt/torch/export/model_config_export.py", line 156, in torch_to_tensorrt_llm_checkpoint
    raise ValueError("Cannot find valid model metadata config in model")
ValueError: Cannot find valid model metadata config in model

What's wrong for this? Is there more detail hands-on guide for deploying quantized model to either tensorrt or tensorrt-llm?

And for quantization, what's the difference in TensorRT-Model-Optimizer and the tensorrt-llm?

**Comment by cjluo-nv** [comment]
> I am trying to deploy my quantized resnet model to tensor-llm.
> 
> By following the "https://nvidia.github.io/TensorRT-Model-Optimizer/deployment/1_tensorrt_llm_deployment.html", I am trying to export it by:
> 
> ```
> from modelopt.torch.export import export_tensorrt_llm_checkpoint
> 
> with torch.inference_mode():
>     export_tensorrt_llm_checkpoint(
>         model_ft,  # The quantized model.
>         'resnet',  # The type of the model as str, e.g gptj, llama or gptnext.
>         torch.float16,  # the weights data type to export the unquantized layers.
>         './',  # The directory where the exported files will be stored.
>         1,  # The number of GPUs used in the inference time for tensor parallelism.
>         1,  # The number of GPUs used in the inference time for pipeline parallelism.
>     )
> ```
> 
> and get following error:
> 
> Cannot export model to the model_config. The modelopt-optimized model state_dict (including the quantization factors) is saved to modelopt_model.0.pth using torch.save for further inspection. Detailed export error: Cannot find valid model metadata config in model Traceback (most recent call last): File "/home/theo/anaconda3/envs/modelopt0.17/lib/python3.10/site-packages/modelopt/torch/export/model_config_export.py", line 446, in export_tensorrt_llm_checkpoint for tensorrt_llm_config, weights in torch_to_tensorrt_llm_checkpoint( File "/home/theo/anaconda3/envs/modelopt0.17/lib/python3.10/site-packages/modelopt/torch/export/model_config_export.py", line 156, in torch_to_tensorrt_llm_checkpoint raise ValueError("Cannot find valid model metadata config in model") ValueError: Cannot find valid model metadata config in model
> 
> What's wrong for this? Is there more detail hands-on guide for deploying quantized model to either tensorrt or tensorrt-llm?
> 
> And for quantization, what's the difference in TensorRT-Model-Optimizer and the tensorrt-llm?

This export_tensorrt_llm_checkpoint API is for TensorRT-LLM deployment. It seems that you are trying to export resnet model which is not transformer based?

**Comment by relaxtheo** [comment]
Thank you for the reply, and I have  2 further questions:

1. For quantized resnet model, I have to deploy it to tensorrt to get the better performance? 
2. For transformer based model? Do you mean the model is base on huggingface transformer library, and the model must in huggingface checkpoint format?

Thank you

**Comment by cjluo-nv** [comment]
> Thank you for the reply, and I have 2 further questions:
> 
> 1. For quantized resnet model, I have to deploy it to tensorrt to get the better performance?
> 2. For transformer based model? Do you mean the model is base on huggingface transformer library, and the model must in huggingface checkpoint format?
> 
> Thank you

1) Yes
2) We support a subset of these LLMs for quantization: Please see the llm_ptq example README.md for the supported list.

**Comment by relaxtheo** [comment]
@cjluo-omniml Thank you very much for the reply, I will do some more tests.

**Comment by relaxtheo** [comment]
After deployment to tensorrt, I can see the quantized model runs a bit faster than original model. 
This issue could be closed.

@cjluo-omniml Thank you very much
