### ISSUE TITLE
Has a plan to support of Jetson AGX Orig??

### ISSUE THREAD

**Issue by Vaderpucong** [NVIDIA/TensorRT-Model-Optimizer#7]
```[tasklist]
### Tasks
```

**Comment by Vaderpucong** [comment]
jetson has a specific version of pytorch that is not compatible with the current TensorRT-Model-Optimizer. If TensorRT-Model-Optimizer is installed, this version is removed, causing the GPU to be unrecognized:
![image](https://github.com/NVIDIA/TensorRT-Model-Optimizer/assets/47764877/6f9b7036-0df7-414a-8340-012d73bd012a)

**Comment by kevalmorabia97** [comment]
model optimizer supports torch>=1.11.
What version are you using?

**Comment by Vaderpucong** [comment]
> model optimizer supports torch>=1.11. What version are you using?

[torch-2.3.0a0+ebedce2.nv24.02-cp310-cp310-linux_aarch64.whl](https://developer.download.nvidia.cn/compute/redist/jp/v60dp/pytorch/torch-2.3.0a0+ebedce2.nv24.02-cp310-cp310-linux_aarch64.whl)

This is a Specific version for Jetson AGX Orin

**Comment by kevalmorabia97** [comment]
Can you check the full installation logs if something else is causing this to be uninstalled. ModelOpt should be compatible with the 2.3.0a0... torch version
