### ISSUE TITLE
Does TensorRT Model Optimizer Support aarch64 ?

### ISSUE THREAD

**Issue by samit-farpoint** [NVIDIA/TensorRT-Model-Optimizer#75]
Hello, 

I am currently working on optimizing LLaMA 3.1 using the TensorRT Model Optimizer and TensorRT-LLM. I would like to know if the Model Optimizer is compatible with the aarch64 architecture as the official documentation states that the system requirement is x86_64.

Thanks!

**Comment by kevalmorabia97** [comment]
Official Grace Hopper aarch64 support will be available from next release (0.19.0). But you can still install current version and try it on Aarch64. While we currently don't guarantee Aarch64 support, many of the features should work fine
