### ISSUE TITLE
No matching distribution found for nvidia-modelopt==0.19.0

### ISSUE THREAD

**Issue by adaber** [NVIDIA/TensorRT-Model-Optimizer#97]
Hi,

I noticed there was a new version (0.19.0, Oct 23) on pypi and tried to pip install it.

'pip install nvidia-modelopt' installs modelopt 0.17.0

'pip install nvidia-modelopt==0.19.0' says 'No matching distribution found for nvidia-modelopt==0.19.0'

Am I missing something or is there a problem with the 0.19.0 distribution ?

Thanks!

**Comment by kevalmorabia97** [comment]
Are you using ModelOpt on Windows? For Windows we have split the release process and the release cadence is slight different than Linux release. Expecting the 0.19 Windows wheels to be available in a few weeks

**Comment by adaber** [comment]
@kevalmorabia97 

Thanks for the quick reply.

That makes sense since I am on Win10. Will you announce the Win release somewhere or should I just try it again in a few weeks ?

Thanks!

**Comment by kevalmorabia97** [comment]
Please keep an eye out on the repository for windows specific examples that we will add with windows official stable release. So far windows feature was experimental and not guaranteed to work. In first windows release, we plan to support ONNX quantization only. Rest features will still be experimental.

Also note that you can check all available versions and wheels on https://pypi.org/simple/nvidia-modelopt/
Currently there is no `*-win_amd64.whl` for `0.19`

**Comment by kevalmorabia97** [comment]
Curious to know what ModelOpt features have you been using on Windows so far so we can better understand what to prioritize for Windows

**Comment by adaber** [comment]
@kevalmorabia97 

Thank you for the quick response and explanation. It's very appreciated.

ONNX quantization is exactly what we need and it's great to hear you'll be focused on it.

So, I will try to explain my workflow to give you a better idea of what is needed. I will try to provide a bit more information and so bare with me, please :) Just trying to help as much as possible.

**Workflow**

1) Train a fully convolutional sem. segm. neural network (UNet, for example) in Pytorch
2) Export it to ONNX using torch.onnx.export
3) Load the "ONNX" model in ONNX Runtime (C++) and create a timing cache (trt engine)


**Input tensor**
There is either one input tensor whose shape is [batchSize-dynamic, height-dynamic, width-dynamic, channelCount-3] or [batchSize-dynamic, channelCount-3, height-dynamic, width-dynamic] so (**[-1, -1,-1, 3] or [-1, 3, -1, -1]**) or

There could be an additional tensor (so, 2 inputs) whose shape is [batchSize-dynamic, height-dynamic, width-dynamic, channelCount-1] or [batchSize-dynamic, channelCount-1, height-dynamic, width-dynamic] (**[-1, -1,-1, 3] or [-1, 3, -1, -1] and [-1, -1,-1, 1] or [-1, 1, -1, -1]**)

**Our current solution**
We've decided to do (implicit PTQ) INT8 quantization using TRT API due to some problems we encountered using the ONNX Runtime TRT wrapper to do it. An INT8 quantized model is then wrapped in an ONNX file which then can be parsed in ONNX Runtime (this feature has been implemented in ONNX Runtime relatively recently). This works but it has its drawbacks.


There are 3 reasons we're interested in this library.

1) Seems that implicit quantization is (will be) superseded by explicit quantization.
2) INT4 quantization, for example, cannot be done using implicit quantization. This is based on the official TRT documentation.
3) This library would allow us to create an "ONNX" INT8 quantized model which could then be parsed by ONNX Runtime.

So, explicit PTQ INT8 quantization of fully convolutional semantic segmentation, fully convolutional classification and non-fully convolutional classification neural nets with 1 or more inputs containing dynamic dimensions is what we plan to use this library for. Doing this on GPUs is a must since there could be hundreds or thousands of calibration images.


**Dynamic dims and GPU support**
It seems that the latest version of Model Opt supports 1 or more inputs containing dynamic dimensions and GPU which is great (haven't tested it yet).

**INT8 quantization algorithm**
There is one thing left that is also very important. It is the INT8 quantization algorithm that this library uses. The TRT's **EntropyCalibrator2** algorithm does a very good job with our models (CNNs) (the TRT documentation mentions that **EntropyCalibrator2** should be used with CNNs). I haven't been able to perform any tests on Model Opt's INT8 quantization algorithms  because the previous version didn't support tensors with dynamic dimensions. I also haven't had time to look at Model Opt's source code but it would be great if the INT8 quantization algorithm you use were similar to the one used by TRT's **EntropyCalibrator2**.

I know that you also suggest to use Model Opt's "Entropy" for CNNs but I am not sure how similar/different your Entropy algorithm is compared to the TRT's **EntropyCalibrator** and **EntropyCalibrator2** algorithms. I didn't get good results using the TRT's **EntropyCalibrator** algorithm, for example. I've done a very thorough test of the results we got using **EntropyCalibrator2**, though and they were pretty good. I calculated and compared IoU, Precision, Recall and F1 using the ground truth, FP32, FP16 and INT8 outputs along with the visual inspection.

I hope this was helpful. Please, let me know if you need someone to be an early tester. Would be more than happy to help!

Thank you again for your time and help!

**Comment by kevalmorabia97** [comment]
Thanks a lot for the details. For now I would suggest you stick with 0.17 version until 0.19 is available. Alternatively you can get started on WSL to use the linux release

**Comment by adaber** [comment]
Thank you, kevalmorabia97!
